### PR TITLE
Milestone 1: Basic Project Structure

### PR DESCRIPTION
**Pull request by moinkhanif**
This milestone covers the basic setup required for getting started with this project. 
It includes the following:
- Initializing React app.
- Customizing the app file and removing default code.
- Installing required packages:
   -  `prop-types`
   -  `redux`
   -  `react-redux`
- Deploying the project to Heroku using `create-react-app-buildpack`

### CODE REVIEW

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
### Status: Changes Required :gear:

**Hello @moinkhanif,**
Thank you for implementing most of the requirements from the first milestone of the project. Required packages are added, the linter is well configured, and the app is available online. But some changes are still required. Please consider the following points.

**[Required]** Commit messages should be capitalized. Please check the requirement. [Reference](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

**[Required]** Remove all the unnecessary images and files. For example, existing logos from react-create-app are not required.

**Please make the required changes and submit for another code review.
If you have any queries regarding this review, message me on slack Suman Shrestha.**

**Comment by moinkhanif** [comment]
> ### Status: Changes Required ⚙️
> **Hello @moinkhanif,**
> Thank you for implementing most of the requirements from the first milestone of the project. Required packages are added, the linter is well configured, and the app is available online. But some changes are still required. Please consider the following points.
> 
> **[Required]** Commit messages should be capitalized. Please check the requirement. [Reference](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> 
> **[Required]** Remove all the unnecessary images and files. For example, existing logos from react-create-app are not required.
> 
> **Please make the required changes and submit for another code review. If you have any queries regarding this review, message me on slack Suman Shrestha.**

Hey @sumancrest0001,  I'll be capitalizing my commit messages from now on. Thanks for pointing it out. However, I had already removed the logo and related files from `src`. In my recent commit, I have removed the styles related to the logo as well. Hope this is what you meant in the review.

Edit: I just realized that the logo images were also available in the `public` folder. I have deleted them 👍🏼

**Review by shshamim63 — APPROVED** [review]
## Status :tada: Approved
___
Hi @moinkhanif :wave: 
First of all, thank you very much for adding a summary of the action that you have taken after the review as a comment. Keep this up. Now regarding your project, you have covered all the necessary changes except updating the commit messages. You mentioned, you will keep that in mind, but it is better to know how to change your pushed commit messages. Well, you can check out this [video](https://www.youtube.com/watch?v=ROl1wbQGHMk). As any crucial changes were not left behind :+1: from me. You can go ahead.
___
### Shakhawat Hossain

**Comment by moinkhanif** [comment]
@shshamim63 Thank you for the video link. I have updated the commits accordingly.

**Pull request merged**
